name: escuelas

packages:
  - escuelas_client/
  - escuelas_flutter/
  - escuelas_server/
  - escuelas_commons/

scripts:
  # runs "flutter pub <arg(s)>" in all packages
  pub: melos exec -c 1 -- flutter pub "$@"
  servergen:
    run: melos exec --scope="*server*" -- "serverpod generate"
  # format all packages' files except for generated files
  format:exclude: >
    melos exec -c 1 -- \
      "find $MELOS_PACKAGE_PATH -name '*.dart' \
          ! -name '*.freezed.dart' \
          ! -name '*.g.dart' \
          ! -name '*.mocks.dart' \
          ! -path '*/l10n/*' \
          ! -name '*.pb*.dart' \
          ! -path '*/.*/*' \
          | xargs dart format --set-exit-if-changed"

  # run build_runner to generate code in all packages
  generate: >
    melos exec -c 1 --fail-fast --depends-on="build_runner" -- \
      dart run build_runner build --delete-conflicting-outputs

  # run gen-l10n to generate localizations in all packages
  gen-l10n: >
    melos exec -c 1 --fail-fast --file-exists="lib/l10n.dart" -- \
     flutter gen-l10n

  # collect coverage information for all packages
  coverage: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      flutter test --coverage && melos run coverage:cleanup

  shorebirdpatch:
    run: melos exec --scope="*server*" -- "shorebird patch"
  runserver:
    run: melos exec --scope="*server*" -- "dart bin/main.dart --mode staging"
  buildwebdev:
    run: melos exec --scope="*flutter*" -- "flutter clean && flutter build web -t lib/main_development.dart"
  buildwebstag:
    run: melos exec --scope="*flutter*" -- "flutter clean && flutter build web -t lib/main_staging.dart"
  buildwebprod:
    run: melos exec --scope="*flutter*" -- "flutter clean && flutter build web -t lib/main_production.dart"
  l10n:
    run: melos exec --scope="*flutter*" -- "flutter gen-l10n"
  releasePatchApk:
    run: melos exec --scope="*flutter*" -- "shorebird patch android --target lib/main_production.dart --flavor production"
  releaseProdApk:
    run: melos exec --scope="*flutter*" -- "shorebird release android --target lib/main_production.dart --flavor production --artifact apk"
  releaseProdIos:
    run: melos exec --scope="*flutter*" -- "shorebird release ios --target lib/main_production.dart --flavor production"
  iconos:
    run: melos exec --depends-on="flutter_launcher_icons" -- "dart run flutter_launcher_icons"
  splash:
    run: melos exec --depends-on="flutter_native_splash" -- "dart run flutter_native_splash:create --flavors main,development,staging,production,dev,stg"
  visuals:
    description: "Generates icons and splash screens for all packages"
    run: melos run iconos && melos run splash
