name: escuelas

packages:
  - escuelas_client/
  - escuelas_flutter/
  - escuelas_server/
  - escuelas_commons/

scripts:
  pubget:
    run: melos exec "flutter pub get"
  servergen:
    run: melos exec --scope="*server*" -- "serverpod generate"
  runserver:
    run: melos exec --scope="*server*" -- "dart bin/main.dart --mode staging"
  buildwebdev:
    run: melos exec --scope="*flutter*" -- "flutter clean && flutter build web -t lib/main_development.dart"
  buildwebstag:
    run: melos exec --scope="*flutter*" -- "flutter clean && flutter build web -t lib/main_staging.dart"
  buildwebprod:
    run: melos exec --scope="*flutter*" -- "flutter clean && flutter build web -t lib/main_production.dart"
  l10n:
    run: melos exec --scope="*flutter*" -- "flutter gen-l10n"
  releaseStg:
    run: melos exec --scope="*flutter*" -- "flutter gen-l10n"
  releaseProd:
    run: melos exec --scope="*flutter*" -- "shorebird release android --target lib/main_production.dart --flavor production --artifact apk"

