apiServer: 
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http
insightsServer: 
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http
webServer: 
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http
database: 
  host: aws-0-sa-east-1.pooler.supabase.com
  port: 6543
  name: postgres
  user: postgres.mvdsvzvejhmrnxgdfdwz
  password: L86Grm9pso3LyUdA
redis: 
  enabled: false
  host: redis.private-staging.examplepod.com
  port: 6379
